version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: aoswald-mtg-practice-table_web_1
      APP_PORT: 3100
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/a0swald/mtg-practice-table:latest
    restart: on-failure
    init: true
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3100
      MTG_DATA_DIR: /app/data
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
